package models.mirror

data class FourPlebsPost(
    var doc_id : String,
    var num : String,
    var subnum : String,
    var thread_num : String,
    var op : String,
    var timestamp : Long,
    var timestamp_expired : String,
    var capcode : String,
    var email : String?,
    var name : String?,
    var trip : String?,
    var title : String?,
    var comment : String?,
    var poster_hash : String?,
    var poster_country : String,
    var sticky : String,
    var locked : String,
    var deleted : String,
    var nreplies : String?,
    var nimages : String?,
    var fourchan_date : String, // "10\/28\/17(Sat)11:36",
    var comment_sanitized : String,
    var comment_processed : String,
    var formatted : Boolean,
    var title_processed : String,
    var name_processed : String,
    var email_processed : String?,
    var trip_processed : String?,
    var poster_hash_processed : String,
    var poster_country_name : String,
    var poster_country_name_processed : String,
    var exif : String?,
    var troll_country_code : Boolean,
    var troll_country_name : String,
    var media : FourChanPostMedia?,
    var board : FourChanPostBoard
) {
    data class FourChanPostBoard(var name : String, var shortname : String)
    data class FourChanPostMedia(
        var media_id : String,
        var spoiler : String,
        var preview_orig : String,
        var media : String,
        var preview_op : String,
        var preview_reply : String?,
        var preview_w : String,
        var preview_h : String,
        var media_filename : String,
        var media_w : String,
        var media_h : String,
        var media_size : String,
        var media_hash : String,
        var media_orig : String,
        var exif : String?,
        var total : String,
        var banned : String,
        var media_status : String,
        var safe_media_hash : String,
        var remote_media_link : String?,
        var media_link : String, //"https:\/\/img.4plebs.org\/boards\/pol\/image\/1509\/20\/1509204991202.jpg",
        var thumb_link : String, //"https:\/\/img.4plebs.org\/boards\/pol\/thumb\/1509\/20\/1509204991202s.jpg",
        var media_filename_processed : String
    )
}