package models.mirror

data class InfChThread(
    var no : Long,
    var com : String,
    var name : String,
    var trip : String,
    var time : Long,
    var omitted_posts : Int,
    var omitted_images : Int,
    var replies : Int,
    var images : Int,
    var sticky : Int,
    var locked : Int,
    var cyclical : String,
    var bumplocked : String,
    var last_modified : Long,
    var tn_h : Int,
    var tn_w : Int,
    var h : Int,
    var w : Int,
    var fsize : Long,
    var filename : String?,
    var ext : String?,
    var tim : String?,
    var fpath : Int,
    var spoiler : Int,
    var md5 : String,
    var resto : Int
)