package models.mirror

data class InfChThread(
    var no : Long = 0,
    var com : String = "",
    var name : String = "",
    var trip : String = "",
    var time : Long = 0,
    var omitted_posts : Int = 0,
    var omitted_images : Int = 0,
    var replies : Int = 0,
    var images : Int = 0,
    var sticky : Int = 0,
    var locked : Int = 0,
    var cyclical : String = "",
    var bumplocked : String = "",
    var last_modified : Long = 0,
    var tn_h : Int = 0,
    var tn_w : Int = 0,
    var h : Int = 0,
    var w : Int = 0,
    var fsize : Long = 0,
    var filename : String? = null,
    var ext : String? = null,
    var tim : String? = null,
    var fpath : Int = 0,
    var spoiler : Int = 0,
    var md5 : String = "",
    var resto : Int = 0
)