package models.q

class Abbreviations {
    companion object {
        val dict : Map<String, String> = hashMapOf(
			Pair("\\+\\+\\+", "House of Saud"),
			Pair("\\+\\+", "Rothschild family"),
			Pair("\\+", "Soros family"),
			Pair("187", "police code for Murder"),
			Pair("4,10,20", "DJT, Donald J. Trump"),
			Pair("7TH FLOOR", "A group of US State Department officials who met regularly on the 7th floor of the Harry S. Truman Building in Washington, DC, that was exposed in Autumn 2016"),
			Pair("7th Floor", "A group of US State Department officials who met regularly on the 7th floor of the Harry S. Truman Building in Washington, DC, that was exposed in Autumn 2016"),
			Pair("ADM R", "Admiral Rogers, Director of NSA"),
			Pair("Adm R\\.", "Admiral Rogers, Director of NSA"),
			Pair("Adm R", "Admiral Rogers, Director of NSA"),
			Pair("AF1", "Air Force 1, POTUS plane"),
			Pair("AG", "Attorney General"),
			Pair("AL", "Al Franken, Senator of Minnesota"),
			Pair("Alice and Wonderland", "Hillary Clinton and the Bloody Saudi Arabia"),
			Pair("AM", "Andrew McCabe"),
            Pair("#2", "Andrew McCabe"),
			Pair("ANON", "Anonymous"),
			Pair("ANTIFA", "Anti-Fascists, Soros backed domestic terrorists"),
			Pair("AS", "Adam Schiff or Antonin Scalia"),
			Pair("ATL", "Atlanta, state capital of Georgia"),
			Pair("AUS", "Australia"),
			Pair("AW", "Anthony Weiner"),
			Pair("BC", "Bill Clinton"),
			Pair("BDT", "Blunt & Direct Time"),
			Pair("BIS", "Bank for International Settlements"),
			Pair("BOB", "Robert Mueller former Director of FBI"),
			Pair("BO", "Barack Obama or Board Owner"),
			Pair("BHO", "Barack (Hussein) Obama"),
			Pair("BOD", "Board of Directors"),
			Pair("BP", "Border Patrol"),
			Pair("BUZZF", "BuzzFeed"),
			Pair("C-INFO", "Classified information"),
			Pair("CA", "Canada"),
			Pair("CC", "Chelsea Clinton"),
			Pair("CEO", "Chief Executive Officer"),
			Pair("CFR", "Council on Foreign Relations"),
			Pair("CF", "Clinton Foundation"),
			Pair("CLAS", "Classified"),
			Pair("Clowns In America", "CIA, Central Intelligence Agency"),
			Pair("Clowns", "CIA, Central Intelligence Agency"),
			Pair("CLOWNS", "CIA, Central Intelligence Agency"),
			Pair("Clown", "CIA, Central Intelligence Agency"),
			Pair("CLOWN", "CIA, Central Intelligence Agency"),
            Pair("C-A", "CIA, Central Intelligence Agency"),
			Pair("C-intel", "Counter-intelligence"),
			Pair("CM", "CodeMonkey, 8chan Administrator"),
			Pair("COC", "Chain of Command"),
			Pair("COMMS", "Communications"),
			Pair("comm", "Committee"),
			Pair("Crooked H", "Hillary Clinton"),
			Pair("CS", "Chuck Schumer or Civil Service"),
			Pair("CTR", "Correct The Record"),
			Pair("DACA", "Deferred Action for Childhood Arrivals"),
			Pair("DC", "District of Columbia"),
			Pair("DEFCON", "DEFense readiness CONdition"),
			Pair("Defcon", "DEFense readiness CONdition"),
			Pair("DHS", "Department of Homeland Security"),
			Pair("DJT", "Donald J. Trump, President Of The United States"),
			Pair("DNC", "Democratic National Committee"),
			Pair("DOD", "Department of Defense"),
			Pair("DOE", "Department of Energy"),
			Pair("DOJ", "Department of Justice"),
            Pair("D-J", "Department of Justice"),
			Pair("DOPEY", "Alwaleed bin Talal"),
			Pair("Dopey", "Alwaleed bin Talal"),
			Pair("D's", "Democrats"),
			Pair("DWS", "Debbie Wasserman Schultz"),
			Pair("EBS", "Emergency Broadcast System"),
			Pair("EMP", "Electromagnetic Pulse"),
			Pair("EMS", "Emergency Messaging System or Emergency Medical Services"),
			Pair("EM", "Elon Musk"),
			Pair("EO", "Executive Order"),
			Pair("ES", "Eric Schmidt"),
			Pair("EU", "European Union"),
			Pair("F&F", "Fast and Furious (Feinstein's failed gun sale attempt)"),
			Pair("f2f", "Face-to-Face"),
			Pair("FBI", "Federal Bureau of Investigation"),
			Pair("FB", "Facebook"),
            Pair("F-I", "Federal Bureau of Investigation"),
			Pair("FED", "Federal Reserve or Federal"),
			Pair("FF", "False flag"),
			Pair("FISA", "Foreign Intelligence Surveillance Act"),
			Pair("FLYNN", "Michael Flynn, former National Security Advisor to President Trump"),
			Pair("GEORGE", "GS"),
			Pair("GER", "Germany"),
			Pair("GITMO", "Guantanamo Bay Naval Base military prison and detention camp"),
			Pair("GOOG", "Google"),
			Pair("GS", "George Soros"),
			Pair("G", "Google"),
			Pair("HA", "Huma Abedin"),
			Pair("HEC", "House Ethics Committee"),
			Pair("HI", "Hawaii"),
			Pair("HK", "Hong Kong"),
			Pair("HRC", "Hillary Rodham Clinton"),
			Pair("HS", "Homeland Security"),
            Pair("Huma", "Huma Abedin"),
			Pair("HUMA", "Huma Abedin or Harvard University Muslim Alumni"),
			Pair("HUSSEIN", "Barack (Hussein) Obama"),
			Pair("Hussein", "Barack (Hussein) Obama"),
			Pair("H-wood", "Hollywood"),
			Pair("HW", "Hollywood"),
			Pair("H", "Haiti"),
			Pair("ICBM", "Intercontinental Ballistic Missle"),
			Pair("IC", "Intelligence Community"),
			Pair("IDEN", "Identification"),
			Pair("ID", "Identification"),
			Pair("IG", "Inspector General"),
			Pair("Inc", "Include"),
			Pair("INTEL", "Intelligence"),
			Pair("intel", "Intelligence"),
			Pair("IRS", "Internal Revenue Service"),
			Pair("ISIS", "Islamic State of Iraq and Syria or Israeli Secret Intelligence Service"),
            Pair("JACK", "Jack Dorsey"),
			Pair("JA", "Julian Assange"),
        	Pair("JB", "John Brennan, Former CIA Director"),
			Pair("JC", "James Clapper (Former DNI Director) or James Comey (Former FBI Director)"),
			Pair("JFK", "John Kennedy, former President of the USA before being assassinated in 1962"),
			Pair("JK", "John Kerry or Jared Kushner"),
			Pair("John M", "John Sidney McCain"),
			Pair("JOHNNY", "John Conyers, US Representative for Michigan"),
			Pair("JP", "John Podesta"),
			Pair("JS", "John Solomon"),
			Pair("KKK", "Ku Klux Klan, started by the D's"),
			Pair("LDR", "Lord De Rothschild"),
			Pair("LL", "Loretta Lynch"),
			Pair("LV", "Las Vegas"),
			Pair("L", "Lynn Rothschild"),
			Pair("MAY", "Theresa May, Prime Minister of the United Kingdom"),
			Pair("MAGA", "MAKE AMERICA GREAT AGAIN"),
			Pair("MB", "Muslim Brotherhood"),
			Pair("MI6", "Secret Intelligence Service (United Kingdom)"),
			Pair("MI", "Military Intelligence"),
			Pair("MIL INTEL", "Military Intelligence"),
			Pair("MIL", "Military"),
			Pair("Mil", "Military"),
			Pair("MISINFO", "Misinformation"),
			Pair("ML", "Marshal Law"),
			Pair("MM", "Media Matters or Million"),
			Pair("MS-13", "Mara Salvatrucha (AKA MS or Mara) is an international criminal gang that originated in Los Angeles, California, US in the 1980s."),
			Pair("MS13", "Mara Salvatrucha (AKA MS or Mara) is an international criminal gang that originated in Los Angeles, California, US in the 1980s."),
			Pair("MSM", "Mainstream Media"),
			Pair("MW", "Maxine Waters"),
			Pair("MZ", "Mark Zuckerberg"),
			Pair("NAT SEC", "National Security"),
            Pair("NAT G", "National Guard"),
			Pair("NG", "National Guard"),
			Pair("NK", "North Korea"),
            Pair("NORK", "North Korea"),
            Pair("NOK", "North Korea"),
			Pair("NP", "Non-Profit or Nancy Pelosi"),
			Pair("NSA", "National Security Agency"),
			Pair("NWO", "New World Order"),
			Pair("NYT", "New York Times, American newspaper"),
			Pair("OO", "Oval Office"),
			Pair("OPS", "Operations"),
			Pair("OP", "Original poster or Operation(s)"),
			Pair("OS", "Oversight"),
			Pair("O", "Obama or Olympic"),
			Pair("P_PERS", "President Trump's Personal message to us"),
			Pair("PAK", "Pakistan"),
			Pair("PG", "Pizzagate/pedogate"),
			Pair("PL", "Presidential library"),
			Pair("PM", "Prime Minister"),
			Pair("POS", "Piece of shit"),
			Pair("POTUS", "Donald J. Trump, President Of The United States"),
			Pair("PP", "Planned Parenthood"),
			Pair("PSYOP", "Psychological operation(s)"),
			Pair("PS", "Peter Strzok, FBI agent"),
			Pair("RC", "Registered Charity"),
			Pair("RED RED", "Red Cross"),
			Pair("Renegade", "Barack (Hussein) Obama, Renegade (traitor) was his USSS codename"),
			Pair("RM", "Robert Mueller former directory of FBI"),
			Pair("RNC", "Republican National Committee"),
			Pair("ROTH", "Rothschild"),
			Pair("RR", "Rod Rosenstein (Deputy Attorney General) or Ronald Reagan"),
			Pair("RT", "Real time"),
			Pair("RYAN", "Paul Ryan, Speaker of the House"),
			Pair("R's", "Republicans"),
			Pair("SAP", "Special Access Programs"),
			Pair("SA", "Saudi Arabia"),
			Pair("SC", "Supreme Court"),
			Pair("SD", "State Department"),
			Pair("SEC", "Security or Secure"),
			Pair("SESSIONS", "Jeff Sessions (Attorney General)"),
			Pair("SH", "Steve Huffman, CEO of Reddit"),
			Pair("SID", "John Sidney McCain"),
			Pair("SIS", "Secret Intelligence Service (United Kingdom)"),
			Pair("SK", "South Korea"),
			Pair("SOTU", "State of the Union"),
			Pair("SNOWDEN", "Edward Snowden, former CIA/NSA"),
			Pair("SR", "Susan Rice or Seth Rich"),
			Pair("SS", "Secret Service"),
			Pair("ST", "Seal Team (eg. Seal Team 6)"),
			Pair("TG", "Trey Gowdy"),
			Pair("TP", "Tony Podesta"),
			Pair("TSA", "Transportation Security Administration"),
			Pair("U1", "Uranium One"),
			Pair("UBL", "Osama Bin Laden"),
			Pair("UK", "United Kingdom"),
			Pair("UN", "United Nations"),
			Pair("US-G", "United States Government"),
			Pair("USMC", "United States Marine Corps"),
			Pair("US MIL", "United States Military"),
			Pair("US Mil", "United States Military"),
			Pair("USMIL", "United States Military"),
			Pair("USSS", "United States Secret Service"),
			Pair("US", "United States"),
			Pair("VJ", "Valerie Jarret"),
			Pair("WH", "White House"),
			Pair("WL", "Wikileaks"),
			Pair("We Don't Say His Name", "John McCain"),
			Pair("We don't say his same", "John McCain"),
			Pair("WRWY", "We are with you"),
			Pair("WW", "Worldwide"),
			Pair("W&W", "Wizards and Warlocks"),
			Pair("YT", "Youtube")
        )
    }
}
