package models.q

class Abbreviations {
    companion object {
        val dict : Map<String, String> = hashMapOf(
			Pair("\\+", "Soros family"),
			Pair("\\+\\+", "Rothschild family"),
			Pair("\\+\\+\\+", "House of Saud"),
			Pair("187", "police code for Murder"),
			Pair("4,10,20", "DJT, Donald J. Trump"),
			Pair("ADM R", "Admiral Rogers, Director of NSA"),
			Pair("AF1", "Air Force 1, POTUS plane"),
			Pair("AG", "Attorney General"),
			Pair("AL", "Al Franken, Senator of Minnesota"),
			Pair("Alice and Wonderland", "Hillary Clinton and the Bloody Saudi Arabia"),
			Pair("AM", "Andrew McCabe"),
            Pair("#2", "Andrew McCabe"),
			Pair("ANON", "Anonymous"),
			Pair("ANTIFA", "Anti-Fascists, Soros backed domestic terrorists"),
			Pair("AS", "Adam Schiff or Antonin Scalia"),
			Pair("ATL", "Atlanta, state capital of Georgia"),
			Pair("AUS", "Australia"),
			Pair("BC", "Bill Clinton"),
			Pair("BIS", "Bank for International Settlements"),
			Pair("BOB", "Robert Mueller former Director of FBI"),
			Pair("BO", "Barack Obama or Board Owner"),
			Pair("BHO", "Barack (Hussein) Obama"),
            Pair("HUSSEIN", "Barack (Hussein) Obama"),
            Pair("Renegade", "Barack (Hussein) Obama, Renegade (traitor) was his USSS codename"),
			Pair("BOD", "Board of Directors"),
			Pair("BP", "Border Patrol"),
			Pair("BUZZF", "BuzzFeed"),
			Pair("C-INFO", "Classified information"),
			Pair("CA", "Canada"),
			Pair("CC", "Chelsea Clinton"),
			Pair("CEO", "Chief Executive Officer"),
			Pair("CF", "Clinton Foundation"),
			Pair("CFR", "Council on Foreign Relations"),
			Pair("Clown", "CIA, Central Intelligence Agency"),
			Pair("CLOWN", "CIA, Central Intelligence Agency"),
			Pair("Clowns", "CIA, Central Intelligence Agency"),
			Pair("CLOWNS", "CIA, Central Intelligence Agency"),
            Pair("Clowns In America", "CIA, Central Intelligence Agency"),
            Pair("C-A", "CIA, Central Intelligence Agency"),
			Pair("CM", "CodeMonkey, 8chan Administrator"),
			Pair("COMMS", "Communications"),
			Pair("CS", "Chuck Schumer or Civil Service"),
			Pair("CTR", "Correct The Record"),
			Pair("DC", "District of Columbia"),
			Pair("DHS", "Department of Homeland Security"),
			Pair("DJT", "Donald J. Trump, President Of The United States"),
            Pair("POTUS", "Donald J. Trump, President Of The United States"),
			Pair("DNC", "Democratic National Committee"),
			Pair("DOD", "Department of Defense"),
			Pair("DOE", "Department of Energy"),
			Pair("DOJ", "Department of Justice"),
            Pair("D-J", "Department of Justice"),
			Pair("DOPEY", "Alwaleed bin Talal"),
			Pair("Dopey", "Alwaleed bin Talal"),
			Pair("D's", "Democrats"),
			Pair("DWS", "Debbie Wasserman Schultz"),
			Pair("EBS", "Emergency Broadcast System"),
			Pair("EM", "Elon Musk"),
			Pair("EMP", "Electromagnetic Pulse"),
			Pair("EMS", "Emergency Messaging System or Emergency Medical Services"),
			Pair("EO", "Executive Order"),
			Pair("ES", "Eric Schmidt"),
			Pair("EU", "European Union"),
			Pair("F&F", "Fast and Furious (Feinstein's failed gun sale attempt)"),
			Pair("f2f", "Face-to-Face"),
			Pair("FB", "Facebook"),
			Pair("FBI", "Federal Bureau of Investigation"),
            Pair("F-I", "Federal Bureau of Investigation"),
			Pair("FED", "Federal Reserve or Federal"),
			Pair("FF", "False flag"),
			Pair("FISA", "Foreign Intelligence Surveillance Act"),
			Pair("FLYNN", "Michael Flynn, former National Security Advisor to President Trump"),
			Pair("GEORGE", "GS"),
			Pair("GOOG", "Google"),
			Pair("GITMO", "Guantanamo Bay Naval Base military prison and detention camp"),
			Pair("GS", "George Soros"),
			Pair("Crooked H", "Hillary Clinton"),
			Pair("H", "Haiti"),
			Pair("HI", "Hawaii"),
			Pair("HK", "Hong Kong"),
			Pair("HRC", "Hillary Rodham Clinton"),
			Pair("HS", "Homeland Security"),
			Pair("HA", "Huma Abedin"),
            Pair("Huma", "Huma Abedin"),
			Pair("HUMA", "Harvard University Muslim Alumni"),
			Pair("H-wood", "Hollywood"),
			Pair("IC", "Intelligence Community"),
			Pair("ID", "Identification"),
            Pair("IDEN", "Identification"),
			Pair("IRS", "Internal Revenue Service"),
			Pair("ISIS", "Islamic State of Iraq and Syria or Israeli Secret Intelligence Service"),
			Pair("JA", "Julian Assange"),
            Pair("JACK", "Jack Dorsey"),
        	Pair("JB", "John Brennan, Former CIA Director"),
			Pair("JC", "James Clapper (Former DNI Director) or James Comey (Former FBI Director)"),
			Pair("JFK", "John Kennedy, former President of the USA before being assassinated in 1962"),
			Pair("JOHNNY", "John Conyers, US Representative for Michigan"),
			Pair("JK", "John Kerry or Jared Kushner"),
			Pair("JS", "John Solomon"),
			Pair("KKK", "Ku Klux Klan, started by the D's"),
			Pair("L", "Lynn Rothschild"),
			Pair("LDR", "Lord De Rothschild"),
			Pair("LL", "Loretta Lynch"),
			Pair("LV", "Las Vegas"),
			Pair("MAY", "Theresa May, Prime Minister of the United Kingdom"),
			Pair("MAGA", "MAKE AMERICA GREAT AGAIN"),
			Pair("MB", "Muslim Brotherhood"),
			Pair("MI", "Military Intelligence"),
			Pair("ML", "Marshal Law"),
			Pair("MM", "Media Matters or Million"),
			Pair("MS-13", "Latino Drug Cartel"),
			Pair("MSM", "Mainstream Media"),
			Pair("MW", "Maxine Waters"),
			Pair("MZ", "Mark Zuckerberg"),
			Pair("NG", "National Guard"),
            Pair("NAT G", "National Guard"),
			Pair("NK", "North Korea"),
            Pair("NORK", "North Korea"),
            Pair("NOK", "North Korea"),
			Pair("NP", "Non-Profit or Nancy Pelosi"),
			Pair("NSA", "National Security Agency"),
			Pair("NWO", "New World Order"),
			Pair("NYT", "New York Times, American newspaper"),
			Pair("O", "Obama"),
			Pair("OO", "Oval Office"),
			Pair("OP", "Original poster or Operation(s)"),
			Pair("P_PERS", "President Trump's Personal message to us"),
			Pair("PG", "Pizzagate/pedogate"),
			Pair("PL", "Presidential library"),
			Pair("PM", "Prime Minister"),
			Pair("POS", "Piece of shit"),
			Pair("PP", "Planned Parenthood"),
			Pair("PS", "Peter Strzok, FBI agent"),
			Pair("RNC", "Republican National Committee"),
			Pair("R's", "Republicans"),
			Pair("RED RED", "Red Cross"),
			Pair("ROTH", "Rothschild"),
			Pair("RR", "Rod Rosenstein (Deputy Attorney General) or Ronald Reagan"),
			Pair("RT", "Real time"),
			Pair("RYAN", "Paul Ryan, Speaker of the House"),
			Pair("SA", "Saudi Arabia"),
			Pair("SAP", "Special Access Programs"),
			Pair("SC", "Supreme Court"),
			Pair("SD", "State Department"),
			Pair("SEC", "Security or Secure"),
			Pair("SESSIONS", "Jeff Sessions (Attorney General)"),
			Pair("SH", "Steve Huffman, CEO of Reddit"),
			Pair("SID", "John Sidney McCain"),
            Pair("We Don't Say His Name", "John McCain"),
            Pair("John M", "John Sidney McCain"),
			Pair("SIS", "Secret Intelligence Service (in the United Kingdom)"),
			Pair("SK", "South Korea"),
			Pair("SOTU", "State of the Union"),
			Pair("SNOWDEN", "Edward Snowden, former CIA/NSA"),
			Pair("SR", "Susan Rice or Seth Rich"),
			Pair("SS", "Secret Service"),
			Pair("ST", "Seal Team (eg. Seal Team 6)"),
			Pair("TG", "Trey Gowdy"),
			Pair("TSA", "Transportation Security Administration"),
			Pair("U1", "Uranium One"),
			Pair("UBL", "Osama Bin Laden"),
			Pair("UN", "United Nations"),
			Pair("US", "United States"),
			Pair("USMC", "United States Marine Corps"),
			Pair("USSS", "United States Secret Service"),
			Pair("VJ", "Valerie Jarret"),
			Pair("WH", "White House"),
			Pair("WL", "Wikileaks"),
			Pair("WRWY", "We are with you"),
			Pair("WW", "Worldwide")
        )
    }
}
